//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_Dier
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public a_Dier()
        {
            this.a_GekochteDieren = new HashSet<a_Gekocht_dier>();
        }
    
        public int Id { get; set; }
        public int eigenaar_Id { get; set; }
        public string type { get; set; }
        public Nullable<decimal> basisprijs { get; set; }
        public Nullable<int> aantal { get; set; }
    
        public virtual a_Speler a_Speler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_Gekocht_dier> a_GekochteDieren { get; set; }
    }
}
