//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_Gereedschap
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public a_Gereedschap()
        {
            this.Compatibiliteiten = new HashSet<a_Compatibiliteit>();
            this.GehuurdGereedschappen = new HashSet<a_GehuurdGereedschap>();
            this.GekochtGereedschappen = new HashSet<a_GekochtGereedschap>();
            this.Huurlijst = new HashSet<a_Huurlijst>();
        }
    
        public int Id { get; set; }
        public string type { get; set; }
        public string naam { get; set; }
        public string inhoud { get; set; }
        public Nullable<decimal> Kw_nodig { get; set; }
        public Nullable<decimal> Hp_nodig { get; set; }
        public Nullable<decimal> breedte { get; set; }
        public Nullable<int> max_Snelheid { get; set; }
        public Nullable<decimal> basisprijs { get; set; }
        public Nullable<decimal> basiskost { get; set; }
        public Nullable<decimal> kost_uur { get; set; }
        public Nullable<decimal> kost_dag { get; set; }
        public string merk { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_Compatibiliteit> Compatibiliteiten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_GehuurdGereedschap> GehuurdGereedschappen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_GekochtGereedschap> GekochtGereedschappen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_Huurlijst> Huurlijst { get; set; }
    }
}
