//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_Gekocht_dier
    {
        public int id { get; set; }
        public int speler_id { get; set; }
        public int dier_id { get; set; }
    
        public virtual a_Dier a_Dier { get; set; }
        public virtual a_Speler a_Speler { get; set; }
    }
}
