//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_Opdracht
    {
        public int Id { get; set; }
        public int veld_Id { get; set; }
        public int graansoort_Id { get; set; }
        public Nullable<int> eigenaar_Id { get; set; }
        public decimal beloning { get; set; }
        public string taakomschrijving { get; set; }
    
        public virtual a_Graansoort a_Graansoort { get; set; }
        public virtual a_Speler a_Speler { get; set; }
        public virtual a_Veld a_Veld { get; set; }
    }
}
