//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_Speler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public a_Speler()
        {
            this.a_Dieren = new HashSet<a_Dier>();
            this.a_GehuurdGereedschappen = new HashSet<a_GehuurdGereedschap>();
            this.a_GehuurdVoertuigen = new HashSet<a_GehuurdVoertuig>();
            this.a_GekochtGereedschappen = new HashSet<a_GekochtGereedschap>();
            this.a_GekochtVoertuigen = new HashSet<a_GekochtVoertuig>();

            this.a_Huurlijsten = new HashSet<a_Huurlijst>();

            this.a_Opdrachten = new HashSet<a_Opdracht>();
            this.a_Velden = new HashSet<a_Veld>();
        }
    
        public int Id { get; set; }
        public string naam { get; set; }
        public string geslacht { get; set; }
        public Nullable<int> level { get; set; }
        public Nullable<decimal> kapitaal { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_Dier> a_Dieren { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_GehuurdGereedschap> a_GehuurdGereedschappen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_GehuurdVoertuig> a_GehuurdVoertuigen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_GekochtGereedschap> a_GekochtGereedschappen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_GekochtVoertuig> a_GekochtVoertuigen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

        public virtual ICollection<a_Huurlijst> a_Huurlijsten { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_Opdracht> a_Opdrachten { get; set; }
        public virtual a_Speler a_Speler1 { get; set; }
        public virtual a_Speler a_Speler2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_Veld> a_Velden { get; set; }
    }
}
