//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_Voertuig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public a_Voertuig()
        {
            this.a_Compatibiliteiten = new HashSet<a_Compatibiliteit>();
            this.a_GehuurdVoertuigen = new HashSet<a_GehuurdVoertuig>();
            this.a_GekochtVoertuigen = new HashSet<a_GekochtVoertuig>();
            this.a_Huurlijsten = new HashSet<a_Huurlijst>();
        }
    
        public int Id { get; set; }
        public string type { get; set; }
        public string merk { get; set; }
        public string naam { get; set; }
        public Nullable<int> max_Snelheid { get; set; }
        public Nullable<int> benzine_Inhoud { get; set; }
        public Nullable<decimal> Kw { get; set; }
        public Nullable<decimal> Ph { get; set; }
        public Nullable<decimal> basisprijs { get; set; }
        public Nullable<decimal> basiskost_huur { get; set; }
        public Nullable<decimal> kost_u_huur { get; set; }
        public Nullable<decimal> kost_dag_huur { get; set; }
        public string inhoud { get; set; }
        public Nullable<decimal> breedte { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_Compatibiliteit> a_Compatibiliteiten { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_GehuurdVoertuig> a_GehuurdVoertuigen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_GekochtVoertuig> a_GekochtVoertuigen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<a_Huurlijst> a_Huurlijsten { get; set; }
    }
}
