//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class a_Weerseffect
    {
        public int Id { get; set; }
        public int graansoort_Id { get; set; }
        public int weersomstandigheid_Id { get; set; }
        public string effect { get; set; }
    
        public virtual a_Graansoort a_Graansoort { get; set; }
        public virtual a_Weersomstandigheid a_Weersomstandigheid { get; set; }
    }
}
