//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityFramework_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MyFarmEntities : DbContext
    {
        public MyFarmEntities()
            : base("name=MyFarmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<a_Compatibiliteit> a_Compatibiliteit { get; set; }
        public virtual DbSet<a_Dier> a_Dier { get; set; }
        public virtual DbSet<a_GehuurdGereedschap> a_GehuurdGereedschap { get; set; }
        public virtual DbSet<a_GehuurdVoertuig> a_GehuurdVoertuig { get; set; }
        public virtual DbSet<a_GekochtGereedschap> a_GekochtGereedschap { get; set; }
        public virtual DbSet<a_GekochtVoertuig> a_GekochtVoertuig { get; set; }
        public virtual DbSet<a_Gereedschap> a_Gereedschap { get; set; }
        public virtual DbSet<a_Graanprijs> a_Graanprijs { get; set; }
        public virtual DbSet<a_Graansoort> a_Graansoort { get; set; }
        public virtual DbSet<a_Huurlijst> a_Huurlijst { get; set; }
        public virtual DbSet<a_Opdracht> a_Opdracht { get; set; }
        public virtual DbSet<a_Speler> a_Speler { get; set; }
        public virtual DbSet<a_Veld> a_Veld { get; set; }
        public virtual DbSet<a_Voertuig> a_Voertuig { get; set; }
        public virtual DbSet<a_Weerseffect> a_Weerseffect { get; set; }
        public virtual DbSet<a_Weersomstandigheid> a_Weersomstandigheid { get; set; }
        public virtual DbSet<a_Gekocht_dier> a_Gekocht_dier { get; set; }
    }
}
